### ISSUE TITLE
adding tailwind-css-colorizer-cmp breaks lspkind 'symbol' mode

### ISSUE THREAD

**Issue by let-josh** [joshwashywash/.dotfiles#10]
Refer to https://github.com/roobert/tailwindcss-colorizer-cmp.nvim/issues/4#issuecomment-1450604853

if this gets sorted out, set lspkind's mode back to 'symbol'.

```lua
-- ...
formatting = {
  format = require('lspkind').cmp_format({
    before = require('tailwindcss-colorizer-cmp').formatter,
    mode = 'symbol,
  }),
},
-- ...
```

**Comment by semi710** [comment]
@joshwashywash got the soution for this?
